spring:
  application:
    name: messageBus
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: bqniu
    password: 123456
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
