spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: 123456
    timeout: 30
  application:
    name: jpa-demo
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: password
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create